### PR TITLE
Add support for 🇫🇷 French language

### PR DESCRIPTION
**Pull request by Write**
+ Add shortcut for french team "Paris Saint-Germain" to "Paris-SG" (As Google does)

I also took headers names (C, MJ, G, N, P, Pts) from Google.

Result when team is set 9847 (Paris Saint-Germain):

Capture d’écran   2021-01-01 à 21 45 45

Screenshot from Google: 
image

### CODE REVIEW

**Comment by thejosejorge** [comment]
Hi @Write,

Thank you so much for the pull request!

Just some quick points, to try to get consistency between all languages:

- For "matchRound" why "T"? Looking at www.ligue1.fr I see "J17", should we use "J" instead?
- For "tableHeaderPoints" would you be able to keep it with 2 letters? To keep it consistent, so it would be "PT".
- For "championsLeagueQualification" I see "Q. Ligue des Champions" is too long to fit in the widget. Shall we use "Q. Ligue Champions" instead? And for consistency also change "Ligue des Champions" to "Ligue Champions". I had to do the same for Portuguese.
- For "uefaSuperCup" I see "Supercoupe de l'UEFA" is too long to fit in the widget. Shall we use "Supercoupe d'Europe" instead? I saw on Wikipedia it's another way to call it in French?
- I see that on FotMob the shorter version for "Paris Saint-Germain" is "PSG", can we make that the default instead?

**Comment by Write** [comment]
> 
> 
> Hi @Write,
> 
> Thank you so much for the pull request!
> 
> Just some quick points, to try to get consistency between all languages:
> 
>     * For "matchRound" why "T"? Looking at [www.ligue1.fr](http://www.ligue1.fr) I see "J17", should we use "J" instead?
> 
Correct, i wasn't sure about "Round" meaning.

>     * For "tableHeaderPoints" would you be able to keep it with 2 letters? To keep it consistent, so it would be "PT".
Ok

>     * For "championsLeagueQualification" I see "Q. Ligue des Champions" is too long to fit in the widget. Shall we use "Q. Ligue Champions" instead? And for consistency also change "Ligue des Champions" to "Ligue Champions". I had to do the same for Portuguese.
Ok

>     * For "uefaSuperCup" I see "Supercoupe de l'UEFA" is too long to fit in the widget. Shall we use "Supercoupe d'Europe" instead? I saw on Wikipedia it's another way to call it in French?
Ok, perfect.

>     * I see that on FotMob the shorter version for "Paris Saint-Germain" is "PSG", can we make that the default instead?
Yes, we refere to Paris Saint-Germain as "PSG" in France, but i tried to Copy everything from Google. Fixed in next push.

**Review by thejosejorge — APPROVED** [review]

**Comment by thejosejorge** [comment]
Looking good, thank you so much for your support!
I will update the README.md.

**Comment by Write** [comment]
Thanks. I just saw i forgot to change replaceText() to PSG instead of Paris-SG

**Comment by thejosejorge** [comment]
No worries, I will change it in the next commit!

**Pull request merged**
